name: Deploy
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout bash-scripts repo
        uses: actions/checkout@v4
        with:
          repository: wozorio/bash-scripts
          path: bash-scripts

      - name: Login to Azure
        run: |
          ./bash-scripts/azure-cli-login.sh \
            ${{ secrets.SUBSCRIPTION_ID }} \
            ${{ secrets.SERVICE_PRINCIPAL_ID }} \
            ${{ secrets.SERVICE_PRINCIPAL_SECRET }} \
            ${{ secrets.TENANT_ID }}

      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.10"

      - name: Setup Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - uses: pulumi/actions@v5
        with:
          command: up
          stack-name: playground
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }} \
          ARM_CLIENT_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }} \
          ARM_CLIENT_SECRET: ${{ secrets.SERVICE_PRINCIPAL_SECRET }} \
          ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
