name: Deploy
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.10"

      - name: Setup Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - uses: pulumi/actions@v6
        with:
          command: up
          stack-name: playground
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }} \
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }} \
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }} \
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
